### ISSUE TITLE
Storage write rejected - version check failed

### ISSUE THREAD

**Issue by justinbalaguer** [heroiclabs/nakama-unity#150] opened 2023-01-28 16:03 UTC
Suddenly have this error when using `WriteStorageObjectsAsync`

![image](https://user-images.githubusercontent.com/26339491/215276563-ab5b46ed-4ffe-484f-8132-dce3f1707e86.png)

code is similar to sample here https://heroiclabs.com/docs/nakama/concepts/storage/collections/#conditional-writes
```csharp
var saveGame = "{ \"progress\": 50 }";

var objectIds = await client.WriteStorageObjectsAsync(session, new [] { 
  new WriteStorageObject
  {
      Collection = "saves",
      Key = "savegame",
      Value = saveGame,
      Version = "<version>"
  }
});
```

Tried restarting the server and deleting saved `account` and `storage` still having that error.

**Comment by novabyte** [comment] 2023-01-28 17:54
@justinbalaguer What version of the game server do you use?

**Comment by justinbalaguer** [comment] 2023-01-28 18:15
2021.3.7f1

**Comment by justinbalaguer** [comment] 2023-01-28 18:29
> @justinbalaguer What version of the game server do you use?

3.15.0 for nakama
2021.3.7f1 for unity

**Comment by lugehorsam** [comment] 2023-01-28 21:13
@justinbalaguer What are you passing as the version? Is it the value you receive when you get the storage objects, and is your storage key experiencing concurrent writes?

**Comment by justinbalaguer** [comment] 2023-01-29 03:55
`collectionObject` is from a `ScriptableObject`
![image](https://user-images.githubusercontent.com/26339491/215303914-1592c4c8-bc7d-445c-8d5a-6d8ca695d4ab.png)
![image](https://user-images.githubusercontent.com/26339491/215303958-98e0f7a6-5ca9-4bf8-8cb7-bf1948925243.png)

**Comment by lugehorsam** [comment] 2023-01-29 20:35
@justinbalaguer this error means that you are passing a value of `Version` that is different than what the server has for your data. The most likely cause is that you aren't passing the version from the acknowledgment of your last write or "*" if it's your first write: 

https://heroiclabs.com/docs/nakama/concepts/storage/collections/#conditional-writes

Closing because this doesn't seem to be an SDK issue. If you can fully reproduce a bug on the server please file it on our Nakama repo: https://github.com/heroiclabs/nakama

**Closed by lugehorsam** 2023-01-29 20:35 UTC
